// LSL

    llAbs
    llAcos
    llAddToLandBanList
    llAddToLandPassList
    llAdjustSoundVolume
    llAgentInExperience
    llAllowInventoryDrop
    llAngleBetween
    llApplyImpulse
    llApplyRotationalImpulse
    llAsin
    llAtan2
    llAttachToAvatar
    llAttachToAvatarTemp
    llAvatarOnLinkSitTarget
    llAvatarOnSitTarget
    llAxes2Rot
    llAxisAngle2Rot
    llBase64ToInteger
    llBase64ToString
    llBreakAllLinks
    llBreakLink
    llCastRay
    llCeil
    llClearCameraParams
    llClearLinkMedia
    llClearPrimMedia
    llCloseRemoteDataChannel
    llCloud
    llCollisionFilter
    llCollisionSound
    llCollisionSprite
    llCos
    llCreateCharacter
    llCreateKeyValue
    llCreateLink
    llCSV2List
    llDataSizeKeyValue
    llDeleteCharacter
    llDeleteKeyValue
    llDeleteSubList
    llDeleteSubString
    llDetachFromAvatar
    llDetectedGrab
    llDetectedGroup
    llDetectedKey
    llDetectedLinkNumber
    llDetectedName
    llDetectedOwner
    llDetectedPos
    llDetectedRot
    llDetectedTouchBinormal
    llDetectedTouchFace
    llDetectedTouchNormal
    llDetectedTouchPos
    llDetectedTouchST
    llDetectedTouchUV
    llDetectedType
    llDetectedVel
    llDialog
    llDie
    llDumpList2String
    llEdgeOfWorld
    llEjectFromLand
    llEmail
    llEscapeURL
    llEuler2Rot
    llEvade
    llExecCharacterCmd
    llFabs
    llFleeFrom
    llFloor
    llForceMouselook
    llFrand
    llGenerateKey
    llGetAccel
    llGetAgentInfo
    llGetAgentLanguage
    llGetAgentList
    llGetAgentSize
    llGetAlpha
    llGetAndResetTime
    llGetAnimation
    llGetAnimationList
    llGetAnimationOverride
    llGetAttached
    llGetAttachedList
    llGetBoundingBox
    llGetCameraPos
    llGetCameraRot
    llGetCenterOfMass
    llGetClosestNavPoint
    llGetColor
    llGetCreator
    llGetDate
    llGetDayLength
    llGetDayOffset
    llGetDisplayName
    llGetEnergy
    llGetEnv
    llGetEnvironment
    llGetExperienceDetails
    llGetExperienceErrorMessage
    llGetForce
    llGetFreeMemory
    llGetFreeURLs
    llGetGeometricCenter
    llGetGMTclock
    llGetHTTPHeader
    llGetInventoryCreator
    llGetInventoryKey
    llGetInventoryName
    llGetInventoryNumber
    llGetInventoryPermMask
    llGetInventoryType
    llGetKey
    llGetLandOwnerAt
    llGetLinkKey
    llGetLinkMedia
    llGetLinkName
    llGetLinkNumber
    llGetLinkNumberOfSides
    llGetLinkPrimitiveParams
    llGetListEntryType
    llGetListLength
    llGetLocalPos
    llGetLocalRot
    llGetMass
    llGetMassMKS
    llGetMaxScaleFactor
    llGetMemoryLimit
    llGetMinScaleFactor
    llGetMoonDirection
    llGetMoonRotation
    llGetNextEmail
    llGetNotecardLine
    llGetNumberOfNotecardLines
    llGetNumberOfPrims
    llGetNumberOfSides
    llGetObjectAnimationNames
    llGetObjectDesc
    llGetObjectDetails
    llGetObjectMass
    llGetObjectName
    llGetObjectPermMask
    llGetObjectPrimCount
    llGetOmega
    llGetOwner
    llGetOwnerKey
    llGetParcelDetails
    llGetParcelFlags
    llGetParcelMaxPrims
    llGetParcelMusicURL
    llGetParcelPrimCount
    llGetParcelPrimOwners
    llGetPermissions
    llGetPermissionsKey
    llGetPhysicsMaterial
    llGetPos
    llGetPrimitiveParams
    llGetPrimMediaParams
    llGetRegionAgentCount
    llGetRegionCorner
    llGetRegionDayLength
    llGetRegionDayOffset
    llGetRegionFlags
    llGetRegionFPS
    llGetRegionMoonDirection
    llGetRegionMoonRotation
    llGetRegionName
    llGetRegionSunDirection
    llGetRegionSunRotation
    llGetRegionTimeDilation
    llGetRootPosition
    llGetRootRotation
    llGetRot
    llGetScale
    llGetScriptName
    llGetScriptState
    llGetSimStats
    llGetSimulatorHostname
    llGetSPMaxMemory
    llGetStartParameter
    llGetStaticPath
    llGetStatus
    llGetSubString
    llGetSunDirection
    llGetSunRotation
    llGetTexture
    llGetTextureOffset
    llGetTextureRot
    llGetTextureScale
    llGetTime
    llGetTimeOfDay
    llGetTimestamp
    llGetTorque
    llGetUnixTime
    llGetUsedMemory
    llGetUsername
    llGetVel
    llGetWallclock
    llGiveInventory
    llGiveInventoryList
    llGiveMoney
    llGodLikeRezObject
    llGround
    llGroundContour
    llGroundNormal
    llGroundRepel
    llGroundSlope
    llHTTPRequest
    llHTTPResponse
    llInsertString
    llInstantMessage
    llIntegerToBase64
    llJson2List
    llJsonGetValue
    llJsonSetValue
    llJsonValueType
    llKey2Name
    llKeyCountKeyValue
    llKeysKeyValue
    llLinear2sRGB
    llLinkParticleSystem
    llLinkSitTarget
    llList2CSV
    llList2Float
    llList2Integer
    llList2Json
    llList2Key
    llList2List
    llList2ListStrided
    llList2Rot
    llList2String
    llList2Vector
    llListen
    llListenControl
    llListenRemove
    llListFindList
    llListInsertList
    llListRandomize
    llListReplaceList
    llListSort
    llListStatistics
    llLoadURL
    llLog
    llLog10
    llLookAt
    llLoopSound
    llLoopSoundMaster
    llLoopSoundSlave
    llMakeExplosion
    llMakeFire
    llMakeFountain
    llMakeSmoke
    llManageEstateAccess
    llMapDestination
    llMD5String
    llMessageLinked
    llMinEventDelay
    llModifyLand
    llModPow
    llMoveToTarget
    llName2Key
    llNavigateTo
    llOffsetTexture
    llOpenRemoteDataChannel
    llOverMyLand
    llOwnerSay
    llParcelMediaCommandList
    llParcelMediaQuery
    llParseString2List
    llParseStringKeepNulls
    llParticleSystem
    llPassCollisions
    llPassTouches
    llPatrolPoints
    llPlaySound
    llPlaySoundSlave
    llPointAt
    llPow
    llPreloadSound
    llPursue
    llPushObject
    llReadKeyValue
    llRefreshPrimURL
    llRegionSay
    llRegionSayTo
    llReleaseCamera
    llReleaseControls
    llReleaseURL
    llRemoteDataReply
    llRemoteDataSetRegion
    llRemoteLoadScript
    llRemoteLoadScriptPin
    llRemoveFromLandBanList
    llRemoveFromLandPassList
    llRemoveInventory
    llRemoveVehicleFlags
    llReplaceAgentEnvironment
    llRequestAgentData
    llRequestDisplayName
    llRequestExperiencePermissions
    llRequestInventoryData
    llRequestPermissions
    llRequestSecureURL
    llRequestSimulatorData
    llRequestURL
    llRequestUserKey
    llRequestUsername
    llResetAnimationOverride
    llResetLandBanList
    llResetLandPassList
    llResetOtherScript
    llResetScript
    llResetTime
    llReturnObjectsByID
    llReturnObjectsByOwner
    llRezAtRoot
    llRezObject
    llRot2Angle
    llRot2Axis
    llRot2Euler
    llRot2Fwd
    llRot2Left
    llRot2Up
    llRotateTexture
    llRotBetween
    llRotLookAt
    llRotTarget
    llRotTargetRemove
    llRound
    llSameGroup
    llSay
    llScaleByFactor
    llScaleTexture
    llScriptDanger
    llScriptProfiler
    llSendRemoteData
    llSensor
    llSensorRemove
    llSensorRepeat
    llSetAgentEnvironment
    llSetAlpha
    llSetAngularVelocity
    llSetAnimationOverride
    llSetBuoyancy
    llSetCameraAtOffset
    llSetCameraEyeOffset
    llSetCameraParams
    llSetClickAction
    llSetColor
    llSetContentType
    llSetDamage
    llSetForce
    llSetForceAndTorque
    llSetHoverHeight
    llSetInventoryPermMask
    llSetKeyframedMotion
    llSetLinkAlpha
    llSetLinkCamera
    llSetLinkColor
    llSetLinkMedia
    llSetLinkPrimitiveParams
    llSetLinkPrimitiveParamsFast
    llSetLinkTexture
    llSetLinkTextureAnim
    llSetLocalRot
    llSetMemoryLimit
    llSetObjectDesc
    llSetObjectName
    llSetObjectPermMask
    llSetParcelMusicURL
    llSetPayPrice
    llSetPhysicsMaterial
    llSetPos
    llSetPrimitiveParams
    llSetPrimMediaParams
    llSetPrimURL
    llSetRegionPos
    llSetRemoteScriptAccessPin
    llSetRot
    llSetScale
    llSetScriptState
    llSetSitText
    llSetSoundQueueing
    llSetSoundRadius
    llSetStatus
    llSetText
    llSetTexture
    llSetTextureAnim
    llSetTimerEvent
    llSetTorque
    llSetTouchText
    llSetVehicleFlags
    llSetVehicleFloatParam
    llSetVehicleRotationParam
    llSetVehicleType
    llSetVehicleVectorParam
    llSetVelocity
    llSHA1String
    llShout
    llSin
    llSitOnLink
    llSitTarget
    llSleep
    llSound
    llSoundPreload
    llSqrt
    llsRGB2Linear
    llStartAnimation
    llStartObjectAnimation
    llStopAnimation
    llStopObjectAnimation
    llStopHover
    llStopLookAt
    llStopMoveToTarget
    llStopPointAt
    llStopSound
    llStringLength
    llStringToBase64
    llStringTrim
    llSubStringIndex
    llTakeCamera
    llTakeControls
    llTan
    llTarget
    llTargetedEmail
    llTargetOmega
    llTargetRemove
    llTeleportAgent
    llTeleportAgentGlobalCoords
    llTeleportAgentHome
    llTextBox
    llToLower
    llToUpper
    llTransferLindenDollars
    llTriggerSound
    llTriggerSoundLimited
    llUnescapeURL
    llUnSit
    llUpdateCharacter
    llUpdateKeyValue
    llVecDist
    llVecMag
    llVecNorm
    llVolumeDetect
    llWanderWithin
    llWater
    llWhisper
    llWind
    llXorBase64
    llXorBase64Strings
    llXorBase64StringsCorrect 

// OSSL
    osAddAgentToGroup
    osAgentSaveAppearance
    osAvatarName2Key
    osAvatarPlayAnimation
    osAvatarStopAnimation
    osCauseDamage
    osCauseHealing
    osDetectedCountry
    osDropAttachment
    osDropAttachmentAt
    osEjectFromGroup
    osForceAttachToAvatar
    osForceAttachToAvatarFromInventory
    osForceAttachToOtherAvatarFromInventory
    osForceDetachFromAvatar
    osForceDropAttachment
    osForceDropAttachmentAt
    osForceOtherSit
    osGetAgentIP
    osGetAgents
    osGetAgentCountry 
    osGetAvatarHomeURI
    osGetAvatarList
    osGetGender
    osGetHealRate
    osGetHealth
    osGetNumberOfAttachments
    osGrantScriptPermissions
    osInviteToGroup
    osKickAvatar
    osOwnerSaveAppearance
    osRevokeScriptPermissions
    osSetHealRate
    osSetHealth
    osSetOwnerSpeed
    osSetSpeed
    osLocalTeleportAgent
    osTeleportAgent
    osTeleportOwner
    osReplaceAgentEnvironment
    osIsNpc
    osNpcCreate
    osGetNpcList
    osNpcGetPos
    osNpcGetRot
    osNpcGetOwner
    osNpcLoadAppearance
    osNpcMoveTo
    osNpcMoveToTarget
    osNpcPlayAnimation
    osNpcRemove
    osNpcSaveAppearance
    osNpcSay
    osNpcSayTo
    osNpcSetProfileAbout
    osNpcSetProfileImage
    osNpcSetRot
    osNpcShout
    osNpcSit
    osNpcStand
    osNpcStopMoveToTarget
    osNpcStopAnimation
    osNpcTouch
    osNpcWhisper 
    osClearInertia
    osClearObjectAnimations
    osDie
    osForceBreakAllLinks
    osForceBreakLink
    osForceCreateLink
    osGetInertiaData
    osGetInventoryItemKey
    osGetInventoryName
    osGetInventoryDesc
    osGetInventoryLastOwner
    osGetLastChangedEventKey
    osGetLinkNumber
    osGetLinkPrimitiveParams
    osGetPrimitiveParams
    osGetRezzingObject
    osGetSitActiveRange
    osGetLinkSitActiveRange
    osGetStandTarget
    osGetLinkStandTarget
    osMessageAttachments
    osMessageObject
    osSetInertia
    osSetInertiaAsBox
    osSetInertiaAsCylinder
    osSetInertiaAsSphere
    osSetPrimitiveParams
    osSetProjectionParams
    osSetSitActiveRange
    osSetLinkSitActiveRange
    osSetStandTarget
    osSetLinkStandTarget
    osTeleportObject
    osVolumeDetect 
    osDrawEllipse
    osDrawFilledEllipse
    osDrawFilledPolygon
    osDrawFilledRectangle
    osDrawImage
    osDrawLine
    osDrawPolygon
    osDrawRectangle
    osDrawResetTransform
    osDrawRotationTransform
    osDrawScaleTransform
    osDrawText
    osDrawTranslationTransform
    osGetDrawStringSize
    osMovePen
    osSetFontName
    osSetFontSize
    osSetPenCap
    osSetPenColor
    osSetPenSize
    osSetDynamicTextureData
    osSetDynamicTextureDataFace
    osSetDynamicTextureDataBlend 
    osSetDynamicTextureDataBlendFace
    osSetDynamicTextureURL
    osSetDynamicTextureURLBlend
    osSetDynamicTextureURLBlendFace
    osGetNotecard
    osGetNotecardLine
    osGetNumberOfNotecardLines
    osMakeNotecard 
    osAdjustSoundVolume
    osCollisionSound
    osLoopSound
    osLoopSoundMaster
    osLoopSoundSlave
    osPlaySound
    osPlaySoundSlave
    osPreloadSound
    osSetSoundRadius
    osStopSound
    osTriggerSound
    osTriggerSoundLimited 
    osRequestSecureURL
    osRequestURL
    osSetContentType 
    osParcelJoin
    osParcelSubdivide
    osGetParcelDwell
    osSetParcelDetails 
    osGetTerrainHeight
    osSetTerrainHeight
    osSetTerrainTexture
    osSetTerrainTextureHeight
    osTerrainFlush 
    osGetCurrentSunHour
    osGetApparentTime
    osGetApparentTimeString
    osGetApparentRegionTime
    osGetApparentRegionTimeString
    osGetWindParam
    osSetRegionWaterHeight
    osSetWindParam
    osWindActiveModelPluginName
    osReplaceParcelEnvironment
    osReplaceRegionEnvironment
    osResetEnvironment
    osCheckODE
    osGetGridCustom
    osGetGridGatekeeperURI
    osGetGridHomeURI
    osGetGridLoginURI
    osGetGridName
    osGetGridNick
    osGetMapTexture
    osGetPhysicsEngineName
    osGetPhysicsEngineType
    osGetRegionMapTexture
    osGetRegionSize
    osGetRegionStats
    osGetScriptEngineName
    osGetSimulatorMemory
    osGetSimulatorMemoryKB
    osGetSimulatorVersion
    osLoadedCreationDate
    osLoadedCreationID
    osLoadedCreationTime 
    osConsoleCommand
    osRegionNotice
    osRegionRestart
    osSetParcelMediaURL
    osSetParcelMusicURL
    osSetParcelSIPAddress 
    osResetAllScripts 
    osFormatString
    osListenRegex
    osMatchString
    osRegexIsMatch
    osReplaceString
    osStringSubString
    osStringStartsWith
    osStringEndsWith
    osStringIndexOf
    osStringLastIndexOf
    osStringRemove
    osStringReplace 
    osAngleBetween
    osApproxEquals
    osGetPSTWallclock
    osIsUUID
    osIsNotValidNumber
    osKey2Name
    osMax
    osMin
    osRound
    osSHA256
    osSlerp
    osUnixTimeToTimestamp
    osVecDistSquare
    osVecMagSquare 

